/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://uyout5kbhjdxzj53npxqmruebe.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-aw23atnc6ba2jl7osvik7zb4ka",
    "aws_cognito_identity_pool_id": "us-east-1:3066dd7a-afbe-4e85-b5c7-6873871b7e78",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_yi3ggVTiP",
    "aws_user_pools_web_client_id": "3c6bilgb7pmce3m3mjog52iui7",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "FAMILY_NAME",
        "NAME",
        "PHONE_NUMBER"
    ],
    "aws_cognito_mfa_configuration": "OPTIONAL",
    "aws_cognito_mfa_types": [
        "SMS",
        "TOTP"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "lakesidewebsite-storage-64ee15cb110801-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
